// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn4IfDeI_vYuLpznD4lYo_7vS4U3LPrUo',
    appId: '1:161475848297:web:8f1747c96e7d27baab5af8',
    messagingSenderId: '161475848297',
    projectId: 'strona-tako',
    authDomain: 'strona-tako.firebaseapp.com',
    storageBucket: 'strona-tako.appspot.com',
    measurementId: 'G-E6F5CT7BY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6OH-7kGRZLe8eoCzuCIsTja2-1lKERtM',
    appId: '1:161475848297:android:b078487ce0286dd1ab5af8',
    messagingSenderId: '161475848297',
    projectId: 'strona-tako',
    storageBucket: 'strona-tako.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASgOXgqQGuz9sM8LaGv4D6XdtttQ4dhMo',
    appId: '1:161475848297:ios:b5ffe63a9d25515bab5af8',
    messagingSenderId: '161475848297',
    projectId: 'strona-tako',
    storageBucket: 'strona-tako.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASgOXgqQGuz9sM8LaGv4D6XdtttQ4dhMo',
    appId: '1:161475848297:ios:a1829bb9acc21c8bab5af8',
    messagingSenderId: '161475848297',
    projectId: 'strona-tako',
    storageBucket: 'strona-tako.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
